[package]
name = "fuzzy_screen"
version = "0.1.0"
authors = ["Daniel Rank <drank@discover-echo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1"
strsim = "0.9.2"
